frequency: 50

sensor_timeout: 0.1 #
two_d_mode: true    #


odom0: /wheelchair/joint_states #
odom0_config: [false, false, false,
               false, false, false,
               true, true, true,
               false, false, true,
               false, false, false]
odom0_differential: false

map_frame: map #
odom_frame: odom
base_link_frame: base_link
world_frame: odom

predict_to_current_time: true

odom0_queue_size: 10       #
odom0_nodelay: false       #
odom0_differential: false  #
odom0_relative: false      #

process_noise_covariance: [1e-3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, #
                           0, 1e-3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, #
                           0, 0, 1e-6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, #
                           0, 0, 0, 1e-6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, #
                           0, 0, 0, 0, 1e-6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, #
                           0, 0, 0, 0, 0, 1e-6, 0, 0, 0, 0, 0, 0, 0, 0, 0] #